### ISSUE TITLE
skip-appstream-check is ignored

### ISSUE THREAD

**Issue by ilya-fedin** [flathub-infra/flatpak-builder-lint#203]
I'm getting appstream-failed-validation despite having skip-appstream-check being set.

PS: what's the point of having appstream check two times?

**Comment by bbhtt** [comment]
The linter expects the flathub.json to be present in `builddir/build/files` but flatpak-builder doesn't copy anything there.

https://github.com/flathub/flatpak-builder-lint/blob/655d3fbeb53f11dcd54472851aec70472fc19451/flatpak_builder_lint/builddir.py#L112

If you add something in the manifest to copy it to `/app/flathub.json` it should work.

```yaml
- name: flathub-json
  buildsystem: simple
  build-commands:
    - cp flathub.json /${FLATPAK_DEST}/flathub.json
  sources:
  - type: file
    path: flathub.json
```
