### ISSUE TITLE
improper only-arches in yaml manifest causes resulting manifest to build packages for both architectures

### ISSUE THREAD

**Issue by bbhtt** [flathub-infra/flatpak-builder-lint#366]
```yaml
app-id: com.lablicate.OpenChrom
runtime: org.freedesktop.Platform
runtime-version: 23.08
sdk: org.freedesktop.Sdk
command: openchrom
finish-args:
  - --socket=x11
  - --share=ipc
  - --device=dri
  - --share=network
  - --socket=pulseaudio
  - --persist=.openchrom
  - --persist=.eclipseswtchartsettings
  - --filesystem=/tmp:rw

modules:
  - name: openchrom
    buildsystem: simple
    build-options:
      strip: false
      no-debuginfo: true
    build-commands:
      - mv openchrom ${FLATPAK_DEST}/openchrom/
      - mkdir -p ${FLATPAK_DEST}/bin
      - ln -sf ${FLATPAK_DEST}/openchrom/openchrom ${FLATPAK_DEST}/bin/
      - install -Dm644 ${FLATPAK_ID}.desktop ${FLATPAK_DEST}/share/applications/${FLATPAK_ID}.desktop
      - install -Dm644 ${FLATPAK_ID}.png ${FLATPAK_DEST}/share/icons/hicolor/256x256/apps/${FLATPAK_ID}.png
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml ${FLATPAK_DEST}/share/metainfo/${FLATPAK_ID}.metainfo.xml
    sources:
      - type: archive
        only-arches:
          x86_64
        url: https://products.lablicate.com/openchrom/1.5.0/openchrom-lablicate_linux.x86_64_1.5.0.tar.gz
        sha256: 64a8528d889f6a05dffc499206af04e93ee170814700c416183fdf42f4d000eb
        strip-components: 0
        dest: openchrom
      - type: archive
        only-arches:
          aarch64
        url: https://products.lablicate.com/openchrom/1.5.0/openchrom-lablicate_linux.aarch64_1.5.0.tar.gz
        sha256: d3f6ca097398891aca88760aae510ae9ba07c3a33de038021523f1c4a482195b
        strip-components: 0
        dest: openchrom
      - type: file
        path: com.lablicate.OpenChrom.desktop
      - type: file
        path: com.lablicate.OpenChrom.png
      - type: file
        path: com.lablicate.OpenChrom.metainfo.xml
```

becomes

```json
{
  "id" : "com.lablicate.OpenChrom",
  "runtime" : "org.freedesktop.Platform",
  "runtime-version" : "23.08",
  "sdk" : "org.freedesktop.Sdk",
  "command" : "openchrom",
  "modules" : [
    {
      "name" : "openchrom",
      "buildsystem" : "simple",
      "sources" : [
        {
          "dest" : "openchrom",
          "url" : "https://products.lablicate.com/openchrom/1.5.0/openchrom-lablicate_linux.x86_64_1.5.0.tar.gz",
          "sha256" : "64a8528d889f6a05dffc499206af04e93ee170814700c416183fdf42f4d000eb",
          "strip-components" : 0,
          "type" : "archive"
        },
        {
          "dest" : "openchrom",
          "url" : "https://products.lablicate.com/openchrom/1.5.0/openchrom-lablicate_linux.aarch64_1.5.0.tar.gz",
          "sha256" : "d3f6ca097398891aca88760aae510ae9ba07c3a33de038021523f1c4a482195b",
          "strip-components" : 0,
          "type" : "archive"
        },
        {
          "path" : "com.lablicate.OpenChrom.desktop",
          "type" : "file"
        },
        {
          "path" : "com.lablicate.OpenChrom.png",
          "type" : "file"
        },
        {
          "path" : "com.lablicate.OpenChrom.metainfo.xml",
          "type" : "file"
        }
      ],
      "build-options" : {
        "no-debuginfo" : true
      },
      "build-commands" : [
        "mv openchrom ${FLATPAK_DEST}/openchrom/",
        "mkdir -p ${FLATPAK_DEST}/bin",
        "ln -sf ${FLATPAK_DEST}/openchrom/openchrom ${FLATPAK_DEST}/bin/",
        "install -Dm644 ${FLATPAK_ID}.desktop ${FLATPAK_DEST}/share/applications/${FLATPAK_ID}.desktop",
        "install -Dm644 ${FLATPAK_ID}.png ${FLATPAK_DEST}/share/icons/hicolor/256x256/apps/${FLATPAK_ID}.png",
        "install -Dm644 ${FLATPAK_ID}.metainfo.xml ${FLATPAK_DEST}/share/metainfo/${FLATPAK_ID}.metainfo.xml"
      ]
    }
  ],
  "finish-args" : [
    "--socket=x11",
    "--share=ipc",
    "--device=dri",
    "--share=network",
    "--socket=pulseaudio",
    "--persist=.openchrom",
    "--persist=.eclipseswtchartsettings",
    "--filesystem=/tmp:rw"
  ]
}
```
